# Generated by Django 6.0 on 2026-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0077_tagconfig_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
